### PR TITLE
Workspace names for instance profile and role

### PR DESCRIPTION
**Pull request by dav3r**
Add workspace to name of instance profile and instance role (as is our new custom), to avoid name collisions and enable easier identification in console.

### CODE REVIEW

**Review by jsf9k — COMMENTED** [review]
@dav3r, please see cisagov/freeipa-master-tf-module#6.  I think this is a more unique way to identify the instance role and profile.

It may not apply here, but I wanted to throw it out there.  With FreeIPA there can be more than one master or replica in a given workspace, so that's why I needed to change it there.

**Review by felddy — APPROVED** [review]
⭐️⭐️⭐️ ⭐️⭐️⭐️ 
My god, it's full of stars!  
⭐️⭐️⭐️ ⭐️⭐️⭐️

**Comment by dav3r** [comment]
> @dav3r, please see [cisagov/freeipa-master-tf-module#6](https://github.com/cisagov/freeipa-master-tf-module/pull/6). I think this is a more unique way to identify the instance role and profile.
> 
> It may not apply here, but I wanted to throw it out there. With FreeIPA there can be more than one master or replica in a given workspace, so that's why I needed to change it there.

Thanks for the heads-up @jsf9k - after discussing with @felddy, we agreed that your way is a good idea here; implemented in https://github.com/cisagov/openvpn-server-tf-module/pull/3/commits/08838ebec08409cd9a4aea4f4ff6d035c6e01fea.

**Comment by dav3r** [comment]
Actually- I had to use the FQDN since the hostname in this project is literally just the name of the host (slightly different than in [FreeIPA project](https://github.com/cisagov/freeipa-master-tf-module/blob/develop/variables.tf#L31-L32)).  Updated in https://github.com/cisagov/openvpn-server-tf-module/pull/3/commits/a3234ef0807bcb0c60b080aa6e260d86e8bb5966.

**Review by jsf9k — APPROVED** [review]
Like a colossus he doth bestride the world.

**Pull request merged**
