### PR TITLE
Some minor simplifications

### PR DESCRIPTION
**Pull request by jsf9k**
I also pulled in upstream updates.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
This looks solid to me- nice simplifications @jsf9k 🚀 

In addition, I think we can also remove the creation of [`local.cert_bucket_path_arn`](https://github.com/cisagov/openvpn-server-tf-module/blob/78fab088304630d2827ce1cdce483e62cd1ff604/locals.tf#L23-L26), now that it is no longer being used for anything (please double-check that).

**Review by felddy — APPROVED** [review]
This is wonderful!  You've succeeded where I failed!
I was talking to @dav3r yesterday about making a tool that will embed python in yaml since we weren't getting all of the linter love we deserved.  Glad I didn't do that. 

Thank you!  This is really a great improvement!  🎊

**Comment by jsf9k** [comment]
> In addition, I think we can also remove the creation of [`local.cert_bucket_path_arn`](https://github.com/cisagov/openvpn-server-tf-module/blob/78fab088304630d2827ce1cdce483e62cd1ff604/locals.tf#L23-L26), now that it is no longer being used for anything (please double-check that).

Unused variable removed in 59d25ff.

**Review by mcdonnnj — APPROVED** [review]
This is a really nice simplification. Great work. 👍

**Pull request merged**
